<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#1-Introduction" data-toc-modified-id="1-Introduction-1">1 Introduction</a></span></li><li><span><a href="#2-Access-to-data" data-toc-modified-id="2-Access-to-data-2">2 Access to data</a></span></li><li><span><a href="#3-Train-the-classification-algorithms" data-toc-modified-id="3-Train-the-classification-algorithms-3">3 Train the classification algorithms</a></span></li><li><span><a href="#4-Selects-the-algorithm-for-Sentinel-2-MSI-and-Landsat-8-OLI" data-toc-modified-id="4-Selects-the-algorithm-for-Sentinel-2-MSI-and-Landsat-8-OLI-4">4 Selects the algorithm for Sentinel-2 MSI and Landsat-8 OLI</a></span></li><li><span><a href="#5-Exhibits-the-statistical-results-of-the-selected-algorithms" data-toc-modified-id="5-Exhibits-the-statistical-results-of-the-selected-algorithms-5">5 Exhibits the statistical results of the selected algorithms</a></span></li><li><span><a href="#6-Saves-the-algorithms" data-toc-modified-id="6-Saves-the-algorithms-6">6 Saves the algorithms</a></span></li></ul></div>

# 1 Introduction
<hr>

A classification algorithm is trained for Sentinel-2 MSI and Landsat-8 OLI sensors. Each algorithm is composed of two steps; first, the Optical Water Types (OWT) are classified by its shape using the normalized remote sensing reflectance (Rrs) bands of each sensor (e.g., normB2); second, the OWTs 7, 8, and 9 are classified by its Rrs intensity using band B3. In both steps, the Support Vector Machine Classifier (SVMC) is used for training the classification algorithm. The novelty detection is not used in this notebook because all dataset is composed of known OWTs. Novelty detection is only useful when applying to new datasets, such as satellite images.

<img src="Supplementary material/0_Figures/svm_owt_algorithm_flowchart.PNG" style="width:70%">

# 2 Access to data

In [1]:
# library used
import pandas as pd 

# Sentinel-2 MSI normalized bands
msi_norm = pd.read_excel('Supplementary material/3 Optical water types/in_situ_data.xlsx',
                         sheet_name='Sentinel 2 MSI norm bands',
                        index_col=0)

# Sentinel-2 MSI band B3
msi_b3 = pd.read_excel('Supplementary material/3 Optical water types/in_situ_data.xlsx',
                         sheet_name='Sentinel 2 MSI bands',
                        index_col=0)

# Landsat-8 OLI normalized bands
oli_norm = pd.read_excel('Supplementary material/3 Optical water types/in_situ_data.xlsx',
                         sheet_name='Landsat 8 OLI norm bands',
                        index_col=0)

# Landsat-8 OLI band B3
oli_b3 = pd.read_excel('Supplementary material/3 Optical water types/in_situ_data.xlsx',
                         sheet_name='Landsat 8 OLI bands',
                        index_col=0)

# OWTs
owts = pd.read_excel('Supplementary material/3 Optical water types/in_situ_data.xlsx',
                         sheet_name='OWTs',
                        index_col=0)

# OWTs where 7, 8, and 9 are concatenate (for shape classification)
owts_shape = owts.applymap(lambda x: x.replace('OWT 6', 'change').
              replace('OWT 7', 'change').
              replace('OWT 8', 'change').
              replace('change', 'OWT 678'))

# 3 Train the classification algorithms

In [2]:
# library used
import warnings
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import copy as cp

# supress warning
warnings.filterwarnings("ignore")

# dictionaries for saving the accuracy results
msi_ba_dic = {}
msi_precision_dic = {}
msi_recall_dic = {}
msi_cm = {}

oli_ba_dic = {}
oli_precision_dic = {}
oli_recall_dic = {}
oli_cm = {}

# dictionaries for saving the algorithms
msi_svmc_alg = {}
oli_svmc_alg = {}

# interaction for randomly splitting train and test datasets 1000 times
for x in range(1,1000):
    
    # splits the ids into a train (70%) and a test (30%) datasets, weighting the relative proportion of OWTs
    train, test = train_test_split(list(owts.index),
                                   test_size=0.3,
                                   stratify=owts['OWTs'])

    # separates the specific ids for further classifying OWTs into 7, 8, and 9
    train_678 = owts_shape[owts_shape['OWTs'] == 'OWT 678'].index.intersection(train)

    # defines the true values of the test dataset
    true = owts.loc[test,:]

    # creates the arrays for the SVMC algorithm (shape classification)
    msi_shape_x = msi_norm.loc[train,:].values
    msi_shape_y = list(owts_shape.loc[train,'OWTs'])
    
    oli_shape_x = oli_norm.loc[train,:].values
    oli_shape_y = list(owts_shape.loc[train,'OWTs'])
    
    # create the arrays for the SVMC algorithm (intensity classifications)
    msi_678_x = msi_b3.loc[train_678,:].values
    msi_678_y = list(owts.loc[train_678,'OWTs'])
    
    oli_678_x = oli_b3.loc[train_678,:].values
    oli_678_y = list(owts.loc[train_678,'OWTs'])

    # train the shape classification algorithm
    msi_svmc_shape = svm.SVC(C=120,
                             kernel='rbf',
                             decision_function_shape='ovo',
                             class_weight='balanced',
                             probability=True).fit(msi_shape_x,
                                                   msi_shape_y)
    
    oli_svmc_shape = svm.SVC(C=120,
                             kernel='rbf',
                             decision_function_shape='ovo',
                             class_weight='balanced',
                             probability=True).fit(oli_shape_x,
                                                   oli_shape_y)

    # train the intensity classification algorithm
    msi_svmc_678 = svm.SVC(C=120,
                           kernel='rbf',
                           decision_function_shape='ovo',
                           class_weight='balanced',
                           probability=True).fit(msi_678_x,
                                                 msi_678_y)
    
    oli_svmc_678 = svm.SVC(C=120,
                           kernel='rbf',
                           decision_function_shape='ovo',
                           class_weight='balanced',
                           probability=True).fit(oli_678_x,
                                                 oli_678_y)

    # predict the OWTs in the test dataset (shape)
    msi_svmc_predicted = msi_svmc_shape.predict(msi_norm.loc[test,:].values)
    msi_svmc_predicted = pd.DataFrame(msi_svmc_predicted,
                                      index=test,
                                      columns=['msi_predicted'])
    
    oli_svmc_predicted = oli_svmc_shape.predict(oli_norm.loc[test,:].values)
    oli_svmc_predicted = pd.DataFrame(oli_svmc_predicted,
                                      index=test,
                                      columns=['oli_predicted'])

    # predict the OWTs in the test dataset (OWTs 7, 8, and 9)
    msi_owt678_predicted_id = msi_svmc_predicted[msi_svmc_predicted['msi_predicted'] == 'OWT 678'].index
    msi_svmc_predicted_678 = msi_svmc_678.predict(msi_b3.loc[msi_owt678_predicted_id,:].values)
    msi_svmc_predicted_678 = pd.DataFrame(msi_svmc_predicted_678,
                                          index=msi_owt678_predicted_id,
                                          columns=['msi_predicted'])
    
    oli_owt678_predicted_id = oli_svmc_predicted[oli_svmc_predicted['oli_predicted'] == 'OWT 678'].index
    oli_svmc_predicted_678 = oli_svmc_678.predict(oli_b3.loc[oli_owt678_predicted_id,:].values)
    oli_svmc_predicted_678 = pd.DataFrame(oli_svmc_predicted_678,
                                          index=oli_owt678_predicted_id,
                                          columns=['oli_predicted'])

    # concatenate all predicted OWTs
    msi_svmc_predicted.update(msi_svmc_predicted_678)
    oli_svmc_predicted.update(oli_svmc_predicted_678)
    
    # creates an evaluation dataset, concatenate predicted OWTs and the true OWTs
    msi_evaluation = msi_svmc_predicted.join(true)
    oli_evaluation = oli_svmc_predicted.join(true)
    
    # computes balanced accuracy, precision, and recall
    msi_ba = balanced_accuracy_score(msi_evaluation['OWTs'],
                                     msi_evaluation['msi_predicted'])

    msi_report = pd.DataFrame(classification_report(msi_evaluation['OWTs'],
                                                    msi_evaluation['msi_predicted'],
                                                    output_dict=True))
    
    msi_confusion_matrix = confusion_matrix(msi_evaluation['OWTs'],
                                            msi_evaluation['msi_predicted'])
    
    oli_ba = balanced_accuracy_score(oli_evaluation['OWTs'],
                                     oli_evaluation['oli_predicted'])

    oli_report = pd.DataFrame(classification_report(oli_evaluation['OWTs'],
                                                    oli_evaluation['oli_predicted'],
                                                    output_dict=True))
    
    oli_confusion_matrix = confusion_matrix(oli_evaluation['OWTs'],
                                            oli_evaluation['oli_predicted'])
    
    # saves the statistical results
    msi_ba_dic[x] = msi_ba
    msi_precision_dic[x] = msi_report.loc['precision',:]
    msi_recall_dic[x] = msi_report.loc['recall',:]
    msi_cm[x] = msi_confusion_matrix
    
    oli_ba_dic[x] = oli_ba
    oli_precision_dic[x] = oli_report.loc['precision',:]
    oli_recall_dic[x] = oli_report.loc['recall',:]
    oli_cm[x] = oli_confusion_matrix
    
    # saves the algorithms
    msi_svmc_alg[x] = cp.copy([msi_svmc_shape, msi_svmc_678])
    oli_svmc_alg[x] = cp.copy([oli_svmc_shape, oli_svmc_678])

# 4 Selects the algorithm for Sentinel-2 MSI and Landsat-8 OLI
<hr>
Ten thousand algorithms were calibrated for Sentinel-2 MSI and Landsat-8 OLI sensors, where each interaction corresponds to different training and test datasets. The algorithm chosen will be that with the median accuracy.

In [3]:
# creates a table with the accuracies of all algorithms
msi_ba_table = pd.DataFrame(msi_ba_dic.values(), index=msi_ba_dic.keys(), columns=['Accuracy'])
oli_ba_table = pd.DataFrame(oli_ba_dic.values(), index=oli_ba_dic.keys(), columns=['Accuracy'])

# sort accuracy values
msi_ba_table = msi_ba_table.sort_values(by='Accuracy')
oli_ba_table = oli_ba_table.sort_values(by='Accuracy')

# retrieves the algorithm id with the median accuracy
middle_row = round(len(msi_ba_table)/2)

msi_alg_number = msi_ba_table.iloc[middle_row,:].name
oli_alg_number = oli_ba_table.iloc[middle_row,:].name

# 5 Exhibits the statistical results of the selected algorithms

In [4]:
# library used
from IPython.core import display as ICD

# print the accuracy values
print('Sentinel-2 MSI: SVMC accuracy')
ICD.display(msi_ba_table.loc[msi_alg_number,:].round(2)[0])

print('Landsat-8 OLI: SVMC accuracy')
ICD.display(oli_ba_table.loc[oli_alg_number,:].round(2)[0])

Sentinel-2 MSI: SVMC accuracy

0.95

Landsat-8 OLI: SVMC accuracy

0.89

In [5]:
# concatenate the precision of both sensors
precision = pd.DataFrame((msi_precision_dic[msi_alg_number],
                          oli_precision_dic[oli_alg_number]),
                         index=['Sentinel-2 MSI', 'Landsat-8 OLI']).T.iloc[0:8,:]

# concatenate the recall of both sensors
recall = pd.DataFrame((msi_recall_dic[msi_alg_number],
                          oli_recall_dic[oli_alg_number]),
                         index=['Sentinel-2 MSI', 'Landsat-8 OLI']).T.iloc[0:8,:]

In [6]:
print('Precision')
ICD.display(precision.round(2))
print('\n')
print('Recall')
ICD.display(recall.round(2))

Precision

       Sentinel-2 MSI  Landsat-8 OLI
OWT 1            1.00           0.95
OWT 2            1.00           1.00
OWT 3            0.82           0.75
OWT 4            0.80           1.00
OWT 5            1.00           1.00
OWT 6            1.00           1.00
OWT 7            0.97           0.97
OWT 8            1.00           1.00

Recall

       Sentinel-2 MSI  Landsat-8 OLI
OWT 1            0.95           1.00
OWT 2            0.96           0.87
OWT 3            1.00           1.00
OWT 4            1.00           1.00
OWT 5            1.00           0.50
OWT 6            1.00           1.00
OWT 7            0.97           1.00
OWT 8            0.75           0.75

In [7]:
print('Sentinel-2 MSI confusion matrix')
ICD.display(pd.DataFrame(msi_cm[msi_alg_number],
           index=['OWT 1', 'OWT 2',  'OWT 3','OWT 4', 'OWT 5', 'OWT 6', 'OWT 7', 'OWT 8'],
           columns=['OWT 1', 'OWT 2',  'OWT 3','OWT 4', 'OWT 5', 'OWT 6', 'OWT 7', 'OWT 8']))

print('\n')
print('Landsat-8 OLI confusion matrix')
ICD.display(pd.DataFrame(oli_cm[oli_alg_number],
           index=['OWT 1', 'OWT 2',  'OWT 3','OWT 4', 'OWT 5', 'OWT 6', 'OWT 7', 'OWT 8'],
           columns=['OWT 1', 'OWT 2',  'OWT 3','OWT 4', 'OWT 5', 'OWT 6', 'OWT 7', 'OWT 8']))

Sentinel-2 MSI confusion matrix

       OWT 1  OWT 2  OWT 3  OWT 4  OWT 5  OWT 6  OWT 7  OWT 8
OWT 1     18      0      0      1      0      0      0      0
OWT 2      0     22      1      0      0      0      0      0
OWT 3      0      0      9      0      0      0      0      0
OWT 4      0      0      0      4      0      0      0      0
OWT 5      0      0      0      0      2      0      0      0
OWT 6      0      0      0      0      0      5      0      0
OWT 7      0      0      1      0      0      0     30      0
OWT 8      0      0      0      0      0      0      1      3

Landsat-8 OLI confusion matrix

       OWT 1  OWT 2  OWT 3  OWT 4  OWT 5  OWT 6  OWT 7  OWT 8
OWT 1     19      0      0      0      0      0      0      0
OWT 2      0     20      3      0      0      0      0      0
OWT 3      0      0      9      0      0      0      0      0
OWT 4      0      0      0      4      0      0      0      0
OWT 5      1      0      0      0      1      0      0      0
OWT 6      0      0      0      0      0      5      0      0
OWT 7      0      0      0      0      0      0     31      0
OWT 8      0      0      0      0      0      0      1      3

# 6 Saves the algorithms

In [8]:
# library used
import pickle

# saves the algorithms in files, where each file is a list of two algorithms (shape classification and intensity classification)
# Sentinel-2 MSI algorithm
file_pi = open('Supplementary material/3 Optical water types/msi_svmc_owts.obj', 'wb') 
pickle.dump(msi_svmc_alg[msi_alg_number], file_pi)
file_pi.close()

# Lansat-8 OLI algorithm
file_pi = open('Supplementary material/3 Optical water types/oli_svmc_owts.obj', 'wb') 
pickle.dump(oli_svmc_alg[oli_alg_number], file_pi)
file_pi.close()